name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies.
      run: sudo apt install -y -q texlive-full
      
    - name: Build resume.
      run: make
      
    - name: Create release.
      uses: ncipollo/release-action@v1
      with:
        artifacts: ".build/resume.pdf"
        tag: ${{ env.GITHUB_SHA }}
        token: ${{ secrets.GITHUB_TOKEN }}
      
   
