name: Build PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Typst.
      run: brew install typst
      
    - name: Build PDF.
      run: typst compile resume.typ
      
    - name: Create release.
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        files: "resume.pdf"
        automatic_release_tag: "latest"
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
