name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies.
      run: sudo apt update && sudo apt upgrade -y -q && sudo apt install -y -q texlive-full
      
    - name: Build resume.
      run: make
      
    - name: Create release.
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        files: ".build/resume.pdf"
        automatic_release_tag: "latest"
        title: ${{ env.GITHUB_SHA }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
